### ISSUE TITLE
Use labels for phone header titles

### ISSUE THREAD

**Issue by ghermans** [FiveM-Scripts/venomous-freemode#4]
## Home
| Label  | Full text |
| -----  | --------- |
| CELL_1 | Texts |
| CELL_2 | Internet |
| CELL_3 | Camera |
| CELL_4 | Sidetasks |
| CELL_5 | Email |
| CELL_6 | Organizer |
| CELL_7 | Snapmatic |
| CELL_12 | Home |
| CELL_13 | BAWSAQ |
| CELL_14 | More Apps |
| CELL_15 | Spare |
| CELL_16 | Settings |
| CELL_18 | Map |
| CELL_19 | Players |
| CELL_21 | Repeat Play |
| CELL_23 | Check List |
| CELL_25 | Sniper |
| CELL_27 | Zit |
| CELL_28 | Trackify |
| CELL_29 | Job List |
| CELL_30 | Impromptu Race |
| CELL_31 | Media |
| CELL_32 | Quick Save|
| CELL_34 | LOCKED | 
| CELL_35 | Player List |
| CELL_36 | A transparent icon signifies a phone application cannot be launched at that moment in time. |
| CELL_37 | Play Quick Job
| CELL_38 | You cannot use the Snapmatic application while in cover. |
| CELL_39 | Broadcast |

## Settings - backgrounds
| Label    | Full text |
| -------  | ----------- |
| CELL_844 | Purple Glow |
| CELL_845 | Green Squares |
| CELL_846 | Orange Herringbone |
| CELL_847 | Orange Halftone |
| CELL_848 | Green Triangles |
| CELL_849 | Green Shards |
| CELL_850 | Blue Angles |
| CELL_851 | Blue Shards |
| CELL_852 | Blue Circles |
| CELL_853 | Diamonds |
| CELL_854 | Green Glow |
| CELL_855 | Orange 8-Bit |
| CELL_856 | Orange Triangles |

**Comment by vecchiotom** [comment]
ezpz
