### ISSUE TITLE
Error on Character Creation

### ISSUE THREAD

**Issue by Tommo-101** [FiveM-Scripts/venomous-freemode#41]
![image](https://user-images.githubusercontent.com/5807404/47871881-11d25580-de05-11e8-971a-ad97c0e621f8.png)

When using the Character creation and you click save the screen goes black and has a spinning wheel in the bottom right and getting this error in the console.

**Comment by ghermans** [comment]
Make sure you are using the latest version of NativeUILua https://github.com/FrazzIe/NativeUILua    
Since the release versions are not up to date don't download them instead just press the "clone or download" button.
