### ISSUE TITLE
Error when loading into server

### ISSUE THREAD

**Issue by DoyleyXD** [FiveM-Scripts/venomous-freemode#44]
whenever i try to localhost my server (which has venomous freemode installed) i get this:
http://prntscr.com/lztmbo

i have nativeui and ghmattimysql downloaded.

any idea on how to fix?

**Comment by ghermans** [comment]
related to https://github.com/FiveM-Scripts/venomous-freemode/issues/7

**Comment by ghermans** [comment]
Issue should be resolved.
