### ISSUE TITLE
Lambda Menu\Player Skin

### ISSUE THREAD

**Issue by Eclipse00** [FiveM-Scripts/venomous-freemode#48]
I'm not sure if this is for VF or for Lambda (https://forum.fivem.net/t/release-lambda-menu/146).

Whenever a skin change is attempted in Lambda Menu, the "Wasted" action happens, and will continue in a loop until the session has dropped. When VF is disabled this is not an issue. I ran a "Clean" setup with just VF to test\verify it's a conflict. I'm assuming since Lamda is client side script, it's some sort of sync problem with VF seeing the user object change? Any insight would be helpful.

**Comment by ghermans** [comment]
@Eclipse00 this issue should be resolved, please download the latest [update](https://github.com/FiveM-Scripts/venomous-freemode/releases/latest).

**Comment by Eclipse00** [comment]
Worked like a charm, I really appreciate your continued development of this project. Keep up the excellent work.
