### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LoganCyp** [FiveM-Scripts/venomous-freemode#56]
The time of day constantly (every second or two) switches from day time to night time.

**Comment by ghermans** [comment]
It seems that there is a conflict with another resource you are using on your server.

**Comment by LoganCyp** [comment]
Could it be vMenu?

**Comment by ghermans** [comment]
its possible that vMenu has a time feature i dunno as i don't use vMenu.

**Comment by LoganCyp** [comment]
It was vMenu - thanks for the help
