### ISSUE TITLE
I am getting issue with mysql database

### ISSUE THREAD

**Issue by harpreet9629** [FiveM-Scripts/venomous-freemode#64]
I am getting error in my console 
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:924: No such export scalar in resource ghmattimysql
> handler (@vf_base/server/general.lua:76)
![Screenshot_1](https://user-images.githubusercontent.com/26606638/68104446-14c4c200-ff01-11e9-9288-3ab6f4b08070.png)
![Screenshot_2](https://user-images.githubusercontent.com/26606638/68104447-155d5880-ff01-11e9-82df-48fd1240005e.png)

**Comment by ghermans** [comment]
1. Remove your current ghmattimysql folder in case it already exists.
2. Download https://github.com/GHMatti/ghmattimysql/releases/download/1.2.1/ghmattimysql.zip .
3. Extract the zip file and rename the folder to ghmattimysql
4. Go to ghmattimysql/config.json and edit your database name/user/password.
5. Copy / paste the ghmattimysql folder to resources.
6. Open server.cfg and add ensure ghmattimysql.

````
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure NativeUI
ensure ghmattimysql
````
7. Once all the above steps are completed (re)start your server and try if it works.
