### ISSUE TITLE
ghmattimysql errors

### ISSUE THREAD

**Issue by tiger1974** [FiveM-Scripts/venomous-freemode#65]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:924: No such export scalar in resource ghmattimysql
> handler (@vf_base/server/general.lua:76)

I'm also getting this in console
Error loading script server/database.lua in resource vf_base: citizen:/scripting/lua/scheduler.lua:924: No such export execute in resource ghmattimysql
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:924: in metamethod '__index'
        @vf_base/server/database.lua:4: in main chunk
Failed to load script server/database.lua.

**Comment by ghermans** [comment]
1. Remove your current ghmattimysql folder in case it already exists.
2. Download https://github.com/GHMatti/ghmattimysql/releases/download/1.2.1/ghmattimysql.zip .
3. Extract the zip file and rename the folder to ghmattimysql
4. Go to ghmattimysql/config.json and edit your database name/user/password.
5. Copy / paste the ghmattimysql folder to resources.
6. Open server.cfg and add ensure ghmattimysql.

````
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure NativeUI
ensure ghmattimysql
````
7. Once all the above steps are completed (re)start your server and try if it works.

**Comment by tiger1974** [comment]
pretty sure it was the latest release of ghmattimysql, as i just installed it while setting up venomous.. but I'll give that a go, thanks.
