### ISSUE TITLE
Character creator

### ISSUE THREAD

**Issue by ghermans** [FiveM-Scripts/venomous-freemode#7]
Allow players to create a custom mp character

**Comment by djowroots** [comment]
is it possible to save character in db? Im amazed with your job, really. keep it up!

**Comment by sammie110** [comment]
Is this still active?.. hope everyone is healthy and safe

**Comment by ghermans** [comment]
Sure, we only have a delay with the new release

**Comment by sammie110** [comment]
Good to hear :-) .. no rush ofc ;-)... was just curious and checking if im going to contribute.. that it was still active ;-)
